
build:
	javac -cp ../libs/json-simple-1.1.1.jar:../libs/commons-io.jar:../libs/commons-codec.jar:../encrypt/ ./Client.java

client:
	java -cp ../libs/json-simple-1.1.1.jar:../libs/commons-io.jar:../libs/commons-codec.jar:../encrypt/: Client eric localhost 9008

clean:
	rm -rf ./*.class
