
build:
	javac -cp ../libs/json-simple-1.1.1.jar:../libs/commons-io.jar:../libs/commons-codec.jar:../encrypt/ ./Server.java

server:
	java -cp ../libs/json-simple-1.1.1.jar:../libs/commons-io.jar:../libs/commons-codec.jar:../encrypt/: Server 9008

clean:
	rm -rf ./*.class
